#this can help to parse the multi-instance log generated by run_inference_cpu.sh
#(1) throuput: ./parse_log.sh
#(2) latency: ./parse_log.sh --single 


NUM_CORES=`lscpu | grep Core | awk '{print $4}'`
NUM_THREAD=$NUM_CORES
NUM_NUMA=$((`lscpu | grep 'NUMA node(s)'|awk '{print $3}' ` - 1))
THOUPUT=0
LATENCY=0
BATCH_SIZE=16

if [[ "$1" == "--single" ]]; then
  echo "### using single batch size"
  BATCH_SIZE=1
  NUM_THREAD=4
  shift
fi

for task in "QNLI" "MRPC"
do
   TASK_NAME=${task}
   LOG_DIR=$TASK_NAME"_LOG"
   echo "task:" $TASK_NAME
   echo "batch_size:" $BATCH_SIZE
   echo "num_threads:" $NUM_THREAD
   for i in $(seq 0 $NUM_NUMA)
      do
      INT_PER_NODE=$(($NUM_CORES / $NUM_THREAD - 1 ))
      for j in $(seq 0 $INT_PER_NODE)
          do
          grep -rn "100%" $LOG_DIR/${TASK_NAME}_batch_size_${BATCH_SIZE}_instance$(($i*($INT_PER_NODE+1)+$j)).log |awk -F 'Evaluating:' '{print $NF}'\
          |grep -P '\d+' -o > tmp.txt
          THOUPUT_INST=$(awk 'BEGIN{batch_size="'${BATCH_SIZE}'";line=0; its=0; seconds=0;}{if(line==1) its=$0; if(line==3) seconds=60*$0; if(line==4) seconds+=$0; line+=1;}END{print its*batch_size/seconds}' tmp.txt)
          LATENCY_INST=$(awk 'BEGIN{batch_size="'${BATCH_SIZE}'";line=0; its=0; seconds=0;}{if(line==1) its=$0; if(line==3) seconds=60*$0; if(line==4) seconds+=$0; line+=1;}END{print seconds/(its*batch_size)}' tmp.txt)
          if [ $BATCH_SIZE = 1 ]; then
             echo "'${TASK_NAME}_batch_size_${BATCH_SIZE}_instance$(($i*($INT_PER_NODE+1)+$j)).log'" "latency:" $LATENCY_INST "second/sample"
          else
             echo "'${TASK_NAME}_batch_size_${BATCH_SIZE}_instance$(($i*($INT_PER_NODE+1)+$j)).log'" "throuput:" $THOUPUT_INST "samples/second"
          fi 
          THOUPUT=$(awk -v a=$THOUPUT_INST -v b=$THOUPUT 'BEGIN{print a+b}')
          LATENCY=$(awk -v a=$LATENCY_INST -v b=$LATENCY 'BEGIN{print a+b}')
       done
   done
   if [ $BATCH_SIZE = 1 ]; then
      LATENCY=$(awk -v latency_sum=$LATENCY -v num_cores=$NUM_CORES -v num_numa=$NUM_NUMA 'BEGIN{print  latency_sum/((num_cores*(num_numa+1)/4))}')
      echo "Latency": $LATENCY "seconds"
   else
      echo "Throuput:" $THOUPUT
   fi 
done
